# Generated by Django 5.0.3 on 2026-06-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisogestion',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ver_dashboard_gestion', 'Puede ver el dashboard de gestión'), ('consultar_asociados', 'Puede consultar asociados'), ('editar_asociados', 'Puede editar asociados'), ('importar_asociados', 'Puede importar asociados'), ('exportar_asociados', 'Puede exportar asociados'), ('cobrar_cuotas', 'Puede cobrar cuotas'), ('ver_deudores', 'Puede ver deudores'), ('administrar_periodos_cuota', 'Puede administrar períodos de cuota'), ('importar_cuotas_historicas', 'Puede importar cuotas históricas'), ('ver_especificacion', 'Puede ver la especificación del proyecto')], 'verbose_name': 'Permiso de gestión', 'verbose_name_plural': 'Permisos de gestión'},
        ),
    ]
