# Generated by Django 5.0.3 on 2026-08-10 23:45

from django.db import migrations


def eliminar_permiso_dashboard(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="gestion",
        codename="ver_dashboard_gestion",
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0005_agregar_permiso_movimientos_asociado"),
        ("usuarios", "0006_reorganizar_grupos_operativos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisogestion',
            options={'default_permissions': (), 'managed': False, 'permissions': [('consultar_asociados', 'Puede consultar asociados'), ('editar_asociados', 'Puede editar asociados'), ('importar_asociados', 'Puede importar asociados'), ('exportar_asociados', 'Puede exportar asociados'), ('cobrar_cuotas', 'Puede cobrar cuotas'), ('ver_deudores', 'Puede ver deudores'), ('administrar_periodos_cuota', 'Puede administrar períodos de cuota'), ('importar_cuotas_historicas', 'Puede importar cuotas históricas'), ('ver_especificacion', 'Puede ver la especificación del proyecto'), ('ver_design_system', 'Puede ver el design system del proyecto'), ('ver_auditoria', 'Puede ver la auditoría de gestión'), ('ver_movimientos_asociado', 'Puede ver los movimientos de la ficha del asociado')], 'verbose_name': 'Permiso de gestión', 'verbose_name_plural': 'Permisos de gestión'},
        ),
        migrations.RunPython(eliminar_permiso_dashboard, migrations.RunPython.noop),
    ]
