# Generated by Django 5.2.14 on 2026-08-26 14:03

from django.db import migrations


PERMISOS = (
    ("consultar_solicitudes_asociacion", "Puede consultar solicitudes de asociación"),
    ("revisar_solicitudes_asociacion", "Puede revisar solicitudes de asociación"),
    ("completar_solicitudes_asociacion", "Puede completar solicitudes de asociación"),
    ("cancelar_solicitudes_asociacion", "Puede cancelar solicitudes de asociación"),
    ("reenviar_comunicaciones", "Puede reenviar comunicaciones"),
)
GRUPOS = ("Atención al asociado", "Administrador de la mutual")


def crear_y_asignar_permisos(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    content_type, _ = ContentType.objects.get_or_create(
        app_label="gestion",
        model="permisogestion",
    )
    permisos = []
    for codename, name in PERMISOS:
        permiso, _ = Permission.objects.get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permisos.append(permiso)
    for grupo in Group.objects.filter(name__in=GRUPOS):
        grupo.permissions.add(*permisos)


def quitar_permisos(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="gestion",
        content_type__model="permisogestion",
        codename__in=[codename for codename, _ in PERMISOS],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_eliminar_permiso_dashboard_gestion'),
        ('usuarios', '0006_reorganizar_grupos_operativos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisogestion',
            options={'default_permissions': (), 'managed': False, 'permissions': [('consultar_asociados', 'Puede consultar asociados'), ('editar_asociados', 'Puede editar asociados'), ('importar_asociados', 'Puede importar asociados'), ('exportar_asociados', 'Puede exportar asociados'), ('cobrar_cuotas', 'Puede cobrar cuotas'), ('ver_deudores', 'Puede ver deudores'), ('administrar_periodos_cuota', 'Puede administrar períodos de cuota'), ('importar_cuotas_historicas', 'Puede importar cuotas históricas'), ('ver_especificacion', 'Puede ver la especificación del proyecto'), ('ver_design_system', 'Puede ver el design system del proyecto'), ('ver_auditoria', 'Puede ver la auditoría de gestión'), ('ver_movimientos_asociado', 'Puede ver los movimientos de la ficha del asociado'), ('consultar_solicitudes_asociacion', 'Puede consultar solicitudes de asociación'), ('revisar_solicitudes_asociacion', 'Puede revisar solicitudes de asociación'), ('completar_solicitudes_asociacion', 'Puede completar solicitudes de asociación'), ('cancelar_solicitudes_asociacion', 'Puede cancelar solicitudes de asociación'), ('reenviar_comunicaciones', 'Puede reenviar comunicaciones')], 'verbose_name': 'Permiso de gestión', 'verbose_name_plural': 'Permisos de gestión'},
        ),
        migrations.RunPython(crear_y_asignar_permisos, quitar_permisos),
    ]
