# Generated by Django 5.2.14 on 2026-09-10 18:19

from django.db import migrations


def asignar_permisos(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    db = schema_editor.connection.alias
    content_type, _ = ContentType.objects.using(db).get_or_create(app_label="gestion", model="permisogestion")
    definiciones = (
        ("ver_atencion_diaria", "Puede consultar Atención diaria y sus propios cobros", ("Atención al asociado", "Administrador de la mutual")),
        ("ver_cobros_equipo", "Puede consultar los cobros de todo el equipo", ("Administrador de la mutual",)),
    )
    for codename, name, grupos in definiciones:
        permiso, _ = Permission.objects.using(db).get_or_create(content_type=content_type, codename=codename, defaults={"name": name})
        for grupo in Group.objects.using(db).filter(name__in=grupos):
            grupo.permissions.add(permiso)


def quitar_permisos(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.using(schema_editor.connection.alias).filter(
        content_type__app_label="gestion", content_type__model="permisogestion",
        codename__in=("ver_atencion_diaria", "ver_cobros_equipo"),
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_permisogestion_options'),
    ]

    operations = [
        migrations.RunPython(asignar_permisos, quitar_permisos),
        migrations.AlterModelOptions(
            name='permisogestion',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ver_atencion_diaria', 'Puede consultar Atención diaria y sus propios cobros'), ('ver_cobros_equipo', 'Puede consultar los cobros de todo el equipo'), ('consultar_asociados', 'Puede consultar asociados'), ('editar_asociados', 'Puede editar asociados'), ('importar_asociados', 'Puede importar asociados'), ('exportar_asociados', 'Puede exportar asociados'), ('cobrar_cuotas', 'Puede cobrar cuotas'), ('ver_deudores', 'Puede ver deudores'), ('administrar_periodos_cuota', 'Puede administrar períodos de cuota'), ('importar_cuotas_historicas', 'Puede importar cuotas históricas'), ('ver_especificacion', 'Puede ver la especificación del proyecto'), ('ver_design_system', 'Puede ver el design system del proyecto'), ('ver_auditoria', 'Puede ver la auditoría de gestión'), ('ver_movimientos_asociado', 'Puede ver los movimientos de la ficha del asociado'), ('consultar_solicitudes_asociacion', 'Puede consultar solicitudes de asociación'), ('revisar_solicitudes_asociacion', 'Puede revisar solicitudes de asociación'), ('completar_solicitudes_asociacion', 'Puede completar solicitudes de asociación'), ('cancelar_solicitudes_asociacion', 'Puede cancelar solicitudes de asociación'), ('reenviar_comunicaciones', 'Puede reenviar comunicaciones')], 'verbose_name': 'Permiso de gestión', 'verbose_name_plural': 'Permisos de gestión'},
        ),
    ]
