# Generated by Django 5.2.14 on 2026-09-10 20:28

from django.db import migrations


def asignar_permiso(apps, schema_editor):
    db = schema_editor.connection.alias
    content_type, _ = apps.get_model("contenttypes", "ContentType").objects.using(db).get_or_create(app_label="gestion", model="permisogestion")
    permiso, _ = apps.get_model("auth", "Permission").objects.using(db).get_or_create(
        content_type=content_type, codename="ver_metricas", defaults={"name": "Puede consultar el tablero de Métricas"})
    for grupo in apps.get_model("auth", "Group").objects.using(db).filter(name="Administrador de la mutual"):
        grupo.permissions.add(permiso)


def quitar_permiso(apps, schema_editor):
    apps.get_model("auth", "Permission").objects.using(schema_editor.connection.alias).filter(
        content_type__app_label="gestion", content_type__model="permisogestion", codename="ver_metricas").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_permisos_atencion_diaria'),
    ]

    operations = [
        migrations.RunPython(asignar_permiso, quitar_permiso),
        migrations.AlterModelOptions(
            name='permisogestion',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ver_metricas', 'Puede consultar el tablero de Métricas'), ('ver_atencion_diaria', 'Puede consultar Atención diaria y sus propios cobros'), ('ver_cobros_equipo', 'Puede consultar los cobros de todo el equipo'), ('consultar_asociados', 'Puede consultar asociados'), ('editar_asociados', 'Puede editar asociados'), ('importar_asociados', 'Puede importar asociados'), ('exportar_asociados', 'Puede exportar asociados'), ('cobrar_cuotas', 'Puede cobrar cuotas'), ('ver_deudores', 'Puede ver deudores'), ('administrar_periodos_cuota', 'Puede administrar períodos de cuota'), ('importar_cuotas_historicas', 'Puede importar cuotas históricas'), ('ver_especificacion', 'Puede ver la especificación del proyecto'), ('ver_design_system', 'Puede ver el design system del proyecto'), ('ver_auditoria', 'Puede ver la auditoría de gestión'), ('ver_movimientos_asociado', 'Puede ver los movimientos de la ficha del asociado'), ('consultar_solicitudes_asociacion', 'Puede consultar solicitudes de asociación'), ('revisar_solicitudes_asociacion', 'Puede revisar solicitudes de asociación'), ('completar_solicitudes_asociacion', 'Puede completar solicitudes de asociación'), ('cancelar_solicitudes_asociacion', 'Puede cancelar solicitudes de asociación'), ('reenviar_comunicaciones', 'Puede reenviar comunicaciones')], 'verbose_name': 'Permiso de gestión', 'verbose_name_plural': 'Permisos de gestión'},
        ),
    ]
