# Generated by Django 5.0.3 on 2026-06-21 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asociados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_recargo_mora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('importe_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('bonificada', 'Bonificada')], default='pendiente', max_length=20)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='asociados.asociado')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['periodo__ciclo_lectivo__anio', 'periodo__mes'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('billetera_virtual', 'Billetera virtual')], max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='asociados.asociado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='cuotas.cuota')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='cuotas.pago')),
            ],
            options={
                'verbose_name': 'Pago de cuota',
                'verbose_name_plural': 'Pagos de cuota',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(help_text='Mes del período (1 a 12).', verbose_name='mes')),
                ('importe', models.DecimalField(decimal_places=2, help_text='Importe base de la cuota para este período.', max_digits=10, verbose_name='importe')),
                ('importe_recargo_mora', models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo que se suma si la cuota no se paga antes del vencimiento.', max_digits=10, verbose_name='recargo por mora')),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite para pagar sin recargo.', verbose_name='fecha de vencimiento')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este período está activo para generar cuotas.', verbose_name='activo')),
                ('ciclo_lectivo', models.ForeignKey(help_text='Año lectivo al que corresponde este período.', on_delete=django.db.models.deletion.PROTECT, related_name='periodos_cuota', to='asociados.ciclolectivo', verbose_name='ciclo lectivo')),
            ],
            options={
                'verbose_name': 'Período de cuota',
                'verbose_name_plural': 'Períodos de cuota',
                'ordering': ['-ciclo_lectivo__anio', '-mes'],
            },
        ),
        migrations.AddField(
            model_name='cuota',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='cuotas.periodocuota'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['asociado', 'fecha'], name='cuotas_pago_asociad_bef77b_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo'], name='cuotas_pago_metodo_511030_idx'),
        ),
        migrations.AddIndex(
            model_name='pagocuota',
            index=models.Index(fields=['pago'], name='cuotas_pago_pago_id_727e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='pagocuota',
            index=models.Index(fields=['cuota'], name='cuotas_pago_cuota_i_acb623_idx'),
        ),
        migrations.AddIndex(
            model_name='periodocuota',
            index=models.Index(fields=['ciclo_lectivo', 'mes'], name='cuotas_peri_ciclo_l_15ec73_idx'),
        ),
        migrations.AddConstraint(
            model_name='periodocuota',
            constraint=models.UniqueConstraint(fields=('mes', 'ciclo_lectivo'), name='uniq_periodo_mes_ciclo'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['asociado', 'estado'], name='cuotas_cuot_asociad_695bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['periodo'], name='cuotas_cuot_periodo_221ac4_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.UniqueConstraint(fields=('asociado', 'periodo'), name='uniq_cuota_asociado_periodo'),
        ),
    ]
