# Generated by Django 5.0.3 on 2026-06-22 12:45

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_ciclos_para_periodos(apps, schema_editor):
    CicloLectivo = apps.get_model("asociados", "CicloLectivo")
    PeriodoCuota = apps.get_model("cuotas", "PeriodoCuota")
    anios = PeriodoCuota.objects.order_by().values_list("anio", flat=True).distinct()
    for anio in anios:
        CicloLectivo.objects.get_or_create(anio=anio)


def asignar_ciclos_a_periodos(apps, schema_editor):
    CicloLectivo = apps.get_model("asociados", "CicloLectivo")
    PeriodoCuota = apps.get_model("cuotas", "PeriodoCuota")
    ciclos_por_anio = {ciclo.anio: ciclo for ciclo in CicloLectivo.objects.all()}
    for periodo in PeriodoCuota.objects.all():
        ciclo = ciclos_por_anio[periodo.ciclo_lectivo_anio]
        periodo.ciclo_lectivo_id = ciclo.id
        periodo.save(update_fields=["ciclo_lectivo"])


class Migration(migrations.Migration):

    replaces = [('cuotas', '0001_initial'), ('cuotas', '0002_alter_cuota_options_alter_periodocuota_options_and_more')]

    dependencies = [
        ('asociados', '0001_initial'),
        ('asociados', '0002_ciclolectivo_alter_inscripcioncurso_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_recargo_mora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('importe_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('bonificada', 'Bonificada')], default='pendiente', max_length=20)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='asociados.asociado')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['periodo__anio', 'periodo__mes'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('billetera_virtual', 'Billetera virtual')], max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='asociados.asociado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='cuotas.cuota')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='cuotas.pago')),
            ],
            options={
                'verbose_name': 'Pago de cuota',
                'verbose_name_plural': 'Pagos de cuota',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveSmallIntegerField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_recargo_mora', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Periodo de cuota',
                'verbose_name_plural': 'Periodos de cuota',
                'ordering': ['-anio', '-mes'],
                'indexes': [models.Index(fields=['anio', 'mes'], name='cuotas_peri_anio_8def26_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='periodocuota',
            constraint=models.UniqueConstraint(fields=('mes', 'anio'), name='uniq_periodo_mes_anio'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='cuotas.periodocuota'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['asociado', 'fecha'], name='cuotas_pago_asociad_bef77b_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['metodo'], name='cuotas_pago_metodo_511030_idx'),
        ),
        migrations.AddIndex(
            model_name='pagocuota',
            index=models.Index(fields=['pago'], name='cuotas_pago_pago_id_727e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='pagocuota',
            index=models.Index(fields=['cuota'], name='cuotas_pago_cuota_i_acb623_idx'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['asociado', 'estado'], name='cuotas_cuot_asociad_695bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['periodo'], name='cuotas_cuot_periodo_221ac4_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.UniqueConstraint(fields=('asociado', 'periodo'), name='uniq_cuota_asociado_periodo'),
        ),
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['periodo__ciclo_lectivo__anio', 'periodo__mes'], 'verbose_name': 'Cuota', 'verbose_name_plural': 'Cuotas'},
        ),
        migrations.AlterModelOptions(
            name='periodocuota',
            options={'ordering': ['-ciclo_lectivo__anio', '-mes'], 'verbose_name': 'Período de cuota', 'verbose_name_plural': 'Períodos de cuota'},
        ),
        migrations.RemoveConstraint(
            model_name='periodocuota',
            name='uniq_periodo_mes_anio',
        ),
        migrations.RemoveIndex(
            model_name='periodocuota',
            name='cuotas_peri_anio_8def26_idx',
        ),
        migrations.RunPython(
            code=crear_ciclos_para_periodos,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RenameField(
            model_name='periodocuota',
            old_name='anio',
            new_name='ciclo_lectivo_anio',
        ),
        migrations.AddField(
            model_name='periodocuota',
            name='ciclo_lectivo',
            field=models.ForeignKey(blank=True, help_text='Año lectivo al que corresponde este período.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodos_cuota', to='asociados.ciclolectivo', verbose_name='ciclo lectivo'),
        ),
        migrations.RunPython(
            code=asignar_ciclos_a_periodos,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='periodocuota',
            name='ciclo_lectivo',
            field=models.ForeignKey(help_text='Año lectivo al que corresponde este período.', on_delete=django.db.models.deletion.PROTECT, related_name='periodos_cuota', to='asociados.ciclolectivo', verbose_name='ciclo lectivo'),
        ),
        migrations.RemoveField(
            model_name='periodocuota',
            name='ciclo_lectivo_anio',
        ),
        migrations.AlterField(
            model_name='periodocuota',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si este período está activo para generar cuotas.', verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='periodocuota',
            name='fecha_vencimiento',
            field=models.DateField(help_text='Fecha límite para pagar sin recargo.', verbose_name='fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='periodocuota',
            name='importe',
            field=models.DecimalField(decimal_places=2, help_text='Importe base de la cuota para este período.', max_digits=10, verbose_name='importe'),
        ),
        migrations.AlterField(
            model_name='periodocuota',
            name='importe_recargo_mora',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo que se suma si la cuota no se paga antes del vencimiento.', max_digits=10, verbose_name='recargo por mora'),
        ),
        migrations.AlterField(
            model_name='periodocuota',
            name='mes',
            field=models.PositiveSmallIntegerField(help_text='Mes del período (1 a 12).', verbose_name='mes'),
        ),
        migrations.AddIndex(
            model_name='periodocuota',
            index=models.Index(fields=['ciclo_lectivo', 'mes'], name='cuotas_peri_ciclo_l_15ec73_idx'),
        ),
        migrations.AddConstraint(
            model_name='periodocuota',
            constraint=models.UniqueConstraint(fields=('mes', 'ciclo_lectivo'), name='uniq_periodo_mes_ciclo'),
        ),
    ]
