# Generated by Django 5.0.3 on 2026-05-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='importe_recargo_mora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='periodocuota',
            name='importe_recargo_mora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
