# Generated by Django 5.0.3 on 2026-06-03 20:39

import django.db.models.deletion
from django.db import migrations, models


def crear_ciclos_para_periodos(apps, schema_editor):
    CicloLectivo = apps.get_model("asociados", "CicloLectivo")
    PeriodoCuota = apps.get_model("cuotas", "PeriodoCuota")
    anios = PeriodoCuota.objects.order_by().values_list("anio", flat=True).distinct()
    for anio in anios:
        CicloLectivo.objects.get_or_create(anio=anio)


def asignar_ciclos_a_periodos(apps, schema_editor):
    CicloLectivo = apps.get_model("asociados", "CicloLectivo")
    PeriodoCuota = apps.get_model("cuotas", "PeriodoCuota")
    ciclos_por_anio = {ciclo.anio: ciclo for ciclo in CicloLectivo.objects.all()}
    for periodo in PeriodoCuota.objects.order_by("id"):
        ciclo = ciclos_por_anio[periodo.ciclo_lectivo_anio]
        periodo.ciclo_lectivo_id = ciclo.id
        periodo.save(update_fields=["ciclo_lectivo"])


class Migration(migrations.Migration):

    dependencies = [
        ('asociados', '0002_ciclolectivo_alter_inscripcioncurso_options_and_more'),
        ('cuotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuota',
            options={'ordering': ['periodo__ciclo_lectivo__anio', 'periodo__mes'], 'verbose_name': 'Cuota', 'verbose_name_plural': 'Cuotas'},
        ),
        migrations.AlterModelOptions(
            name='periodocuota',
            options={'ordering': ['-ciclo_lectivo__anio', '-mes'], 'verbose_name': 'Período de cuota', 'verbose_name_plural': 'Períodos de cuota'},
        ),
        migrations.RemoveConstraint(
            model_name='periodocuota',
            name='uniq_periodo_mes_anio',
        ),
        migrations.RemoveIndex(
            model_name='periodocuota',
            name='cuotas_peri_anio_8def26_idx',
        ),
        migrations.RunPython(crear_ciclos_para_periodos, migrations.RunPython.noop),
        migrations.RenameField(
            model_name='periodocuota',
            old_name='anio',
            new_name='ciclo_lectivo_anio',
        ),
        migrations.AddField(
            model_name='periodocuota',
            name='ciclo_lectivo',
            field=models.ForeignKey(blank=True, help_text='Año lectivo al que corresponde este período.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodos_cuota', to='asociados.ciclolectivo', verbose_name='ciclo lectivo'),
        ),
        migrations.RunPython(asignar_ciclos_a_periodos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='periodocuota',
            name='ciclo_lectivo',
            field=models.ForeignKey(help_text='Año lectivo al que corresponde este período.', on_delete=django.db.models.deletion.PROTECT, related_name='periodos_cuota', to='asociados.ciclolectivo', verbose_name='ciclo lectivo'),
        ),
        migrations.RemoveField(
            model_name='periodocuota',
            name='ciclo_lectivo_anio',
        ),
        migrations.AlterField(
            model_name='periodocuota',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si este período está activo para generar cuotas.', verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='periodocuota',
            name='fecha_vencimiento',
            field=models.DateField(help_text='Fecha límite para pagar sin recargo.', verbose_name='fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='periodocuota',
            name='importe',
            field=models.DecimalField(decimal_places=2, help_text='Importe base de la cuota para este período.', max_digits=10, verbose_name='importe'),
        ),
        migrations.AlterField(
            model_name='periodocuota',
            name='importe_recargo_mora',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo que se suma si la cuota no se paga antes del vencimiento.', max_digits=10, verbose_name='recargo por mora'),
        ),
        migrations.AlterField(
            model_name='periodocuota',
            name='mes',
            field=models.PositiveSmallIntegerField(help_text='Mes del período (1 a 12).', verbose_name='mes'),
        ),
        migrations.AddIndex(
            model_name='periodocuota',
            index=models.Index(fields=['ciclo_lectivo', 'mes'], name='cuotas_peri_ciclo_l_15ec73_idx'),
        ),
        migrations.AddConstraint(
            model_name='periodocuota',
            constraint=models.UniqueConstraint(fields=('mes', 'ciclo_lectivo'), name='uniq_periodo_mes_ciclo'),
        ),
    ]
