# Generated by Django 5.0.3 on 2026-06-22 13:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados', '0001_initial_squashed_0007_remove_estado_egresado'),
        ('cuotas', '0001_initial_squashed_0002_alter_cuota_options_alter_periodocuota_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuota',
            name='importe_recargo_mora',
        ),
        migrations.RemoveField(
            model_name='periodocuota',
            name='importe_recargo_mora',
        ),
        migrations.AddField(
            model_name='cuota',
            name='importe_recargo_mes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cuota',
            name='importe_recargo_mes_siguiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='periodocuota',
            name='importe_recargo_mes',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Recargo fijo si se paga después del vencimiento pero dentro del mismo mes.', max_digits=10, verbose_name='recargo por mora (mismo mes)'),
        ),
        migrations.AddField(
            model_name='periodocuota',
            name='importe_recargo_mes_siguiente',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text='Recargo fijo si se paga después de que pasó el mes de vencimiento.', max_digits=10, verbose_name='recargo por mora (mes siguiente)'),
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='asociados.asociado')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='cuotas.pago')),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
