# Generated by Django 5.0.3 on 2026-06-22 14:21

from django.db import migrations, models


def normalizar_estados_sacados(apps, schema_editor):
    Cuota = apps.get_model("cuotas", "Cuota")
    Cuota.objects.filter(estado="parcial").update(estado="pendiente")
    Cuota.objects.filter(estado="bonificada").update(estado="pagada")


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0003_remove_cuota_importe_recargo_mora_and_more'),
    ]

    operations = [
        migrations.RunPython(normalizar_estados_sacados, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cuota',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=20),
        ),
    ]
