# Generated by Django 5.2.14 on 2026-09-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0005_periodocuota_generado_el'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='clave_operacion',
            field=models.UUIDField(blank=True, editable=False, help_text='Identifica un envío de cobro para impedir que un reintento cree otro ingreso. Los pagos históricos pueden no tener clave.', null=True, unique=True, verbose_name='clave de operación'),
        ),
    ]
