# Generated by Django 5.0.3 on 2026-08-09 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actor_etiqueta', models.CharField(max_length=150)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('modificar', 'Modificar'), ('cambiar_estado', 'Cambiar estado'), ('vincular', 'Vincular'), ('desvincular', 'Desvincular'), ('anular', 'Anular'), ('eliminar', 'Eliminar')], max_length=30)),
                ('entidad', models.CharField(max_length=150)),
                ('objeto_id', models.CharField(max_length=100)),
                ('objeto_descripcion', models.CharField(max_length=255)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('origen', models.CharField(choices=[('gestion', 'Gestión'), ('admin', 'Admin de Django'), ('importacion', 'Importación'), ('comando', 'Comando'), ('sistema', 'Sistema')], max_length=30)),
                ('operacion_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Eventos de auditoría',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['entidad', 'objeto_id', 'fecha'], name='auditoria_e_entidad_606cd8_idx'), models.Index(fields=['actor', 'fecha'], name='auditoria_e_actor_i_66e9ba_idx'), models.Index(fields=['accion', 'fecha'], name='auditoria_e_accion_c752f1_idx'), models.Index(fields=['operacion_id'], name='auditoria_e_operaci_39e91d_idx')],
            },
        ),
    ]
