# Generated by Django 5.2.14 on 2026-08-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_describir_actor_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoauditoria',
            name='origen',
            field=models.CharField(choices=[('gestion', 'Gestión'), ('admin', 'Admin de Django'), ('importacion', 'Importación'), ('comando', 'Comando'), ('sistema', 'Sistema'), ('sitio_publico', 'Sitio público')], max_length=30),
        ),
    ]
