# Generated by Django 5.2.14 on 2026-08-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_alter_eventoauditoria_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoauditoria',
            name='motivo',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
