# Generated by Django 5.2.14 on 2026-09-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_alter_eventoauditoria_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoauditoria',
            name='origen',
            field=models.CharField(choices=[('gestion', 'Gestión'), ('admin', 'Admin de Django'), ('importacion', 'Importación'), ('comando', 'Comando'), ('sistema', 'Sistema'), ('sitio_publico', 'Sitio público'), ('asociado', 'Asociado')], max_length=30),
        ),
    ]
