# Generated by Django 5.2.14 on 2026-08-26 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Código estable del hecho que origina la comunicación.', max_length=100)),
                ('alcance', models.CharField(choices=[('individual', 'Individual'), ('lote', 'Lote')], max_length=20)),
                ('clave_idempotencia', models.CharField(help_text='Evita registrar dos veces la misma comunicación.', max_length=200, unique=True, verbose_name='clave de idempotencia')),
                ('origen_entidad', models.CharField(max_length=150, verbose_name='entidad de origen')),
                ('origen_id', models.CharField(max_length=100, verbose_name='identificador de origen')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
            ],
            options={
                'verbose_name': 'Comunicación',
                'verbose_name_plural': 'Comunicaciones',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EntregaComunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Correo electrónico')], max_length=20)),
                ('destino', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida'), ('omitida', 'Omitida')], default='pendiente', max_length=20)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultimo_intento_en', models.DateTimeField(blank=True, null=True, verbose_name='último intento')),
                ('enviado_en', models.DateTimeField(blank=True, null=True, verbose_name='enviada el')),
                ('proveedor_id', models.CharField(blank=True, max_length=255, verbose_name='identificador del proveedor')),
                ('ultimo_error', models.CharField(blank=True, max_length=500, verbose_name='último error')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('comunicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='comunicaciones.comunicacion')),
            ],
            options={
                'verbose_name': 'Entrega de comunicación',
                'verbose_name_plural': 'Entregas de comunicaciones',
                'ordering': ['-creado_en', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='comunicacion',
            index=models.Index(fields=['origen_entidad', 'origen_id'], name='comunicacio_origen__f77833_idx'),
        ),
        migrations.AddIndex(
            model_name='entregacomunicacion',
            index=models.Index(fields=['estado', 'creado_en'], name='comunicacio_estado_247046_idx'),
        ),
        migrations.AddIndex(
            model_name='entregacomunicacion',
            index=models.Index(fields=['comunicacion', 'canal'], name='comunicacio_comunic_b3f26c_idx'),
        ),
    ]
