# Generated by Django 5.0.3 on 2026-06-02 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=20)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origen_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('origen_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contables',
                'ordering': ['codigo', 'nombre'],
                'indexes': [models.Index(fields=['tipo', 'activa'], name='contabilida_tipo_6d3f01_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartidaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.CharField(choices=[('debe', 'Debe'), ('haber', 'Haber')], max_length=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='contabilidad.asiento')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Partida de asiento',
                'verbose_name_plural': 'Partidas de asiento',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='asiento',
            index=models.Index(fields=['fecha', 'tipo'], name='contabilida_fecha_1d1eef_idx'),
        ),
        migrations.AddIndex(
            model_name='asiento',
            index=models.Index(fields=['origen_content_type', 'origen_object_id'], name='contabilida_origen__3ba09e_idx'),
        ),
        migrations.AddIndex(
            model_name='partidaasiento',
            index=models.Index(fields=['asiento', 'movimiento'], name='contabilida_asiento_a9f10e_idx'),
        ),
        migrations.AddIndex(
            model_name='partidaasiento',
            index=models.Index(fields=['cuenta'], name='contabilida_cuenta__feb008_idx'),
        ),
    ]
