# Generated by Django 5.2.14 on 2026-08-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_crear_grupos_y_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDatosStaging',
            fields=[
                ('clave', models.CharField(default='actual', editable=False, help_text='Identificador único del estado habilitado para staging.', max_length=20, primary_key=True, serialize=False, verbose_name='clave')),
                ('refresh_id', models.CharField(help_text='Debe coincidir con el epoch privado publicado por la PWA.', max_length=64, verbose_name='identificador del refresco')),
                ('listo_desde', models.DateTimeField(help_text='Momento en que terminó el endurecimiento completo de la copia.', verbose_name='listo desde')),
            ],
            options={
                'verbose_name': 'estado de datos de staging',
                'verbose_name_plural': 'estados de datos de staging',
            },
        ),
    ]
