# Generated by Django 5.0.3 on 2026-06-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre visible del beneficio.', max_length=150, verbose_name='título')),
                ('descripcion', models.TextField(help_text='Texto público que explica el beneficio.', verbose_name='descripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el beneficio se publica en el sitio.', verbose_name='activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Posición usada para ordenar los beneficios publicados.', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
