# Generated by Django 5.0.3 on 2026-06-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el beneficio se publica en el sitio.', verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='descripcion',
            field=models.TextField(help_text='Texto público que explica el beneficio.', verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Posición usada para ordenar los beneficios publicados.', verbose_name='orden'),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='titulo',
            field=models.CharField(help_text='Nombre visible del beneficio.', max_length=150, verbose_name='título'),
        ),
    ]
