# Generated by Django 5.0.3 on 2026-06-23 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0001_initial_squashed_0002_alter_beneficio_activo_alter_beneficio_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre visible de la categoría de productos o servicios.', max_length=150, unique=True, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Texto público que explica la categoría.', verbose_name='descripción')),
                ('etiqueta_icono', models.CharField(blank=True, help_text='Etiqueta textual para elegir o representar un ícono, por ejemplo printer.', max_length=50, verbose_name='etiqueta de ícono')),
                ('texto_cta', models.TextField(blank=True, help_text='Texto de contacto o acción asociado a esta categoría. Los emails y URLs se convierten en enlaces en la web.', verbose_name='texto para call to action')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la categoría se publica en el sitio.', verbose_name='activa')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Posición usada para ordenar las categorías publicadas.', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Categoría de producto o servicio',
                'verbose_name_plural': 'Categorías de productos y servicios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre visible del producto o servicio.', max_length=150, verbose_name='nombre')),
                ('descripcion', models.TextField(help_text='Texto público que explica qué incluye.', verbose_name='descripción')),
                ('es_servicio', models.BooleanField(default=False, help_text='Marcar si el ítem es un servicio. Si no se marca, se interpreta como producto.', verbose_name='es servicio')),
                ('precio_asociados', models.DecimalField(decimal_places=2, help_text='Precio vigente para asociados.', max_digits=10, verbose_name='precio para asociados')),
                ('precio_no_asociados', models.DecimalField(decimal_places=2, help_text='Precio vigente para personas no asociadas.', max_digits=10, verbose_name='precio para no asociados')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el producto o servicio se publica en el sitio.', verbose_name='activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Posición usada para ordenar los productos y servicios publicados.', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Producto o servicio',
                'verbose_name_plural': 'Productos y servicios',
                'ordering': ['categoria__orden', 'orden', 'nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Beneficio',
        ),
        migrations.AddIndex(
            model_name='categoriaproductoservicio',
            index=models.Index(fields=['activa', 'orden'], name='contenidos__activa_a5e8b5_idx'),
        ),
        migrations.AddField(
            model_name='productoservicio',
            name='categoria',
            field=models.ForeignKey(help_text='Categoría pública a la que pertenece este producto o servicio.', on_delete=django.db.models.deletion.PROTECT, related_name='productos_servicios', to='contenidos.categoriaproductoservicio', verbose_name='categoría'),
        ),
        migrations.AddIndex(
            model_name='productoservicio',
            index=models.Index(fields=['activo', 'orden'], name='contenidos__activo_1d5a67_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoservicio',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='uniq_producto_servicio_por_categoria'),
        ),
    ]
