# Generated by Django 5.0.3 on 2026-06-23 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0003_comercio_orden'),
        ('contenidos', '0003_categoriaproductoservicio_productoservicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título visible de la publicidad.', max_length=150, verbose_name='título')),
                ('descripcion', models.TextField(help_text='Texto breve que acompaña la publicidad.', verbose_name='descripción')),
                ('etiqueta_principal', models.CharField(help_text='Etiqueta superior de la card, por ejemplo Alimentos o Servicio.', max_length=80, verbose_name='etiqueta principal')),
                ('etiqueta_secundaria', models.CharField(help_text='Texto destacado de la card, por ejemplo 10% OFF o Nuevo.', max_length=80, verbose_name='etiqueta secundaria')),
                ('foto', models.ImageField(help_text='Imagen horizontal recomendada: 1600x900 px, WebP o JPG, menor a 500 KB.', upload_to='publicidades/', verbose_name='foto')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la publicidad se muestra en la home.', verbose_name='activa')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Posición usada para ordenar las publicidades en la home.', verbose_name='orden')),
                ('comercio', models.ForeignKey(blank=True, help_text='Comercio al que apunta la publicidad, si corresponde.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicidades', to='comercios.comercio', verbose_name='comercio')),
                ('producto_servicio', models.ForeignKey(blank=True, help_text='Producto o servicio al que apunta la publicidad, si corresponde.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicidades', to='contenidos.productoservicio', verbose_name='producto o servicio')),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': 'Publicidades',
                'ordering': ['orden', 'titulo'],
                'indexes': [models.Index(fields=['activa', 'orden'], name='contenidos__activa_42e69a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='publicidad',
            constraint=models.CheckConstraint(check=models.Q(('producto_servicio__isnull', True), ('comercio__isnull', True), _connector='OR'), name='publicidad_un_solo_destino'),
        ),
    ]
