# Generated by Django 5.0.3 on 2026-06-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0004_publicidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicidad',
            name='foto',
            field=models.ImageField(blank=True, help_text='Imagen horizontal recomendada: 1600x900 px, WebP o JPG, menor a 500 KB.', upload_to='publicidades/', verbose_name='foto'),
        ),
    ]
