# Generated by Django 5.0.3 on 2026-08-14 13:22

from django.db import migrations, models


def convertir_servicios_sin_precio(apps, schema_editor):
    ProductoServicio = apps.get_model("contenidos", "ProductoServicio")
    ProductoServicio.objects.filter(
        es_servicio=True,
        precio_asociados=0,
        precio_no_asociados=0,
    ).update(precio_asociados=None, precio_no_asociados=None)


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0005_alter_publicidad_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproductoservicio',
            name='imagen_informativa',
            field=models.ImageField(blank=True, help_text='Imagen compartida por la categoría, por ejemplo una tabla de talles.', upload_to='categorias_productos_servicios/', verbose_name='imagen informativa'),
        ),
        migrations.AddField(
            model_name='categoriaproductoservicio',
            name='titulo_imagen_informativa',
            field=models.CharField(blank=True, help_text='Título público que explica la imagen, por ejemplo Tabla de talles.', max_length=150, verbose_name='título de la imagen informativa'),
        ),
        migrations.AddField(
            model_name='productoservicio',
            name='ciclo_destinatario',
            field=models.CharField(blank=True, choices=[('CB', 'Ciclo Básico'), ('CS', 'Ciclo Superior')], help_text='Ciclo escolar al que se dirige el producto o servicio, si corresponde.', max_length=2, verbose_name='ciclo destinatario'),
        ),
        migrations.AddField(
            model_name='productoservicio',
            name='curso_destinatario',
            field=models.CharField(blank=True, help_text='Año tomado de los cursos cargados, sin distinguir comisión ni turno.', max_length=10, verbose_name='curso destinatario'),
        ),
        migrations.AddField(
            model_name='productoservicio',
            name='foto',
            field=models.ImageField(blank=True, help_text='Fotografía del producto o servicio para su ficha pública.', upload_to='productos_servicios/', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='productoservicio',
            name='precio_asociados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio vigente para asociados.', max_digits=10, null=True, verbose_name='precio para asociados'),
        ),
        migrations.AlterField(
            model_name='productoservicio',
            name='precio_no_asociados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio vigente para personas no asociadas.', max_digits=10, null=True, verbose_name='precio para no asociados'),
        ),
        migrations.RunPython(convertir_servicios_sin_precio, migrations.RunPython.noop),
    ]
