# Generated by Django 5.0.3 on 2026-09-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0006_categoriaproductoservicio_imagen_informativa_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productoservicio',
            name='uniq_producto_servicio_por_categoria',
        ),
        migrations.AlterField(
            model_name='productoservicio',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Texto público que explica qué incluye.', verbose_name='descripción'),
        ),
    ]
