# Generated by Django 5.2.14 on 2026-08-27 03:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0006_categoriaproductoservicio_imagen_informativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre visible de la novedad o evento.', max_length=150, verbose_name='título')),
                ('slug', models.SlugField(help_text='Texto único usado en la dirección pública de la novedad.', max_length=170, unique=True, verbose_name='identificador para URL')),
                ('etiqueta', models.CharField(default='Novedad', help_text='Categoría breve, por ejemplo Próximo evento o Comunidad.', max_length=80, verbose_name='etiqueta')),
                ('resumen', models.TextField(help_text='Descripción breve que se muestra en la tarjeta de la home.', verbose_name='resumen')),
                ('contenido', models.TextField(help_text='Información completa que se muestra en la página de detalle.', verbose_name='contenido')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen horizontal opcional. Se recomienda 1600x900 px, WebP o JPG.', upload_to='novedades/', verbose_name='imagen')),
                ('color', models.CharField(choices=[('azul', 'Azul'), ('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo')], default='azul', help_text='Color de marca usado cuando la novedad no tiene imagen.', max_length=10, verbose_name='color')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, help_text='La novedad se vuelve visible a partir de esta fecha.', verbose_name='fecha de publicación')),
                ('destacada', models.BooleanField(default=False, help_text='Prioriza esta novedad como tarjeta principal en la home.', verbose_name='destacada')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la novedad se publica en el sitio.', verbose_name='activa')),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['-destacada', '-fecha_publicacion', 'titulo'],
                'indexes': [models.Index(fields=['activa', 'fecha_publicacion'], name='contenidos__activa_1a82dd_idx')],
            },
        ),
    ]
