# Generated by Django 5.2.14 on 2026-09-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0007_remove_productoservicio_uniq_producto_servicio_por_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproductoservicio',
            name='etiqueta_icono',
            field=models.CharField(blank=True, help_text='Nombre de un ícono de Bootstrap Icons, por ejemplo printer o tag. <a href="https://icons.getbootstrap.com/" target="_blank" rel="noopener">Elegí el nombre desde la galería de Bootstrap Icons</a>.', max_length=50, verbose_name='etiqueta de ícono'),
        ),
    ]
