# Generated by Django 5.0.3 on 2026-05-22 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='asociados.colegio')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['colegio__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('asociado', 'Asociado'), ('adherente', 'Adherente')], max_length=20)),
                ('numero_asociado', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('token_credencial', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('egresado', 'Egresado')], default='activo', max_length=20)),
                ('fecha_alta', models.DateField()),
                ('fecha_inicio_cobro', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, max_length=255)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asociado', to=settings.AUTH_USER_MODEL)),
                ('curso_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asociados_actuales', to='asociados.curso')),
            ],
            options={
                'verbose_name': 'Asociado',
                'verbose_name_plural': 'Asociados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_lectivo', models.PositiveIntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='asociados.asociado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='asociados.curso')),
            ],
            options={
                'verbose_name': 'Inscripcion a curso',
                'verbose_name_plural': 'Inscripciones a curso',
                'ordering': ['-ciclo_lectivo', '-fecha_desde'],
            },
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['colegio', 'activo'], name='asociados_c_colegio_c5129a_idx'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(fields=('colegio', 'nombre'), name='uniq_curso_por_colegio'),
        ),
        migrations.AddIndex(
            model_name='asociado',
            index=models.Index(fields=['estado', 'tipo'], name='asociados_a_estado_fc7c14_idx'),
        ),
        migrations.AddIndex(
            model_name='asociado',
            index=models.Index(fields=['numero_asociado'], name='asociados_a_numero__2252d2_idx'),
        ),
        migrations.AddIndex(
            model_name='asociado',
            index=models.Index(fields=['fecha_inicio_cobro'], name='asociados_a_fecha_i_3ae177_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcioncurso',
            index=models.Index(fields=['asociado', 'activa'], name='asociados_i_asociad_263939_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcioncurso',
            index=models.Index(fields=['ciclo_lectivo'], name='asociados_i_ciclo_l_767aa4_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscripcioncurso',
            constraint=models.UniqueConstraint(fields=('asociado', 'curso', 'ciclo_lectivo', 'fecha_desde'), name='uniq_inscripcion_historial'),
        ),
    ]
