# Generated by Django 5.0.3 on 2026-06-21 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(help_text='Año del ciclo lectivo.', unique=True, verbose_name='año')),
            ],
            options={
                'verbose_name': 'Ciclo lectivo',
                'verbose_name_plural': 'Ciclos lectivos',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(help_text='Año que cursa, ej: 1ro, 2do, 3ro.', max_length=10, verbose_name='año')),
                ('curso', models.CharField(help_text='División o número de curso, ej: 1ra, 2da, única.', max_length=10, verbose_name='curso')),
                ('division', models.CharField(choices=[('CB', 'Ciclo Básico'), ('CS', 'Ciclo Superior')], default='CB', help_text='Ciclo al que pertenece: CB (Ciclo Básico) o CS (Ciclo Superior).', max_length=2, verbose_name='división')),
                ('turno', models.CharField(choices=[('TM', 'Turno Mañana'), ('TT', 'Turno Tarde')], default='TM', help_text='Turno: TM (Turno Mañana) o TT (Turno Tarde).', max_length=2, verbose_name='turno')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el curso está activo en el sistema.', verbose_name='activo')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['division', 'anio', 'curso', 'turno'],
            },
        ),
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, help_text='Domicilio del asociado.', max_length=255, verbose_name='dirección')),
                ('tipo', models.CharField(choices=[('asociado', 'Asociado'), ('adherente', 'Adherente')], max_length=20)),
                ('numero_asociado', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('token_credencial', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_alta', models.DateField()),
                ('fecha_inicio_cobro', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, max_length=255)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asociado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asociado',
                'verbose_name_plural': 'Asociados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(fields=('anio', 'curso', 'division', 'turno'), name='uniq_curso'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='curso_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asociados_actuales', to='asociados.curso'),
        ),
        migrations.AddIndex(
            model_name='asociado',
            index=models.Index(fields=['estado', 'tipo'], name='asociados_a_estado_fc7c14_idx'),
        ),
        migrations.AddIndex(
            model_name='asociado',
            index=models.Index(fields=['numero_asociado'], name='asociados_a_numero__2252d2_idx'),
        ),
        migrations.AddIndex(
            model_name='asociado',
            index=models.Index(fields=['fecha_inicio_cobro'], name='asociados_a_fecha_i_3ae177_idx'),
        ),
    ]
