# Generated by Django 5.0.3 on 2026-06-03 20:39

import django.db.models.deletion
from django.db import migrations, models


def crear_ciclos_para_inscripciones(apps, schema_editor):
    CicloLectivo = apps.get_model("asociados", "CicloLectivo")
    InscripcionCurso = apps.get_model("asociados", "InscripcionCurso")
    anios = (
        InscripcionCurso.objects.exclude(ciclo_lectivo__isnull=True)
        .values_list("ciclo_lectivo", flat=True)
        .distinct()
    )
    for anio in anios:
        CicloLectivo.objects.get_or_create(anio=anio)


def asignar_ciclos_a_inscripciones(apps, schema_editor):
    CicloLectivo = apps.get_model("asociados", "CicloLectivo")
    InscripcionCurso = apps.get_model("asociados", "InscripcionCurso")
    ciclos_por_anio = {ciclo.anio: ciclo for ciclo in CicloLectivo.objects.all()}
    for inscripcion in InscripcionCurso.objects.all():
        ciclo = ciclos_por_anio[inscripcion.ciclo_lectivo_anio]
        inscripcion.ciclo_lectivo_id = ciclo.id
        inscripcion.save(update_fields=["ciclo_lectivo"])


class Migration(migrations.Migration):

    dependencies = [
        ('asociados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(help_text='Año del ciclo lectivo.', unique=True, verbose_name='año')),
            ],
            options={
                'verbose_name': 'Ciclo lectivo',
                'verbose_name_plural': 'Ciclos lectivos',
                'ordering': ['-anio'],
            },
        ),
        migrations.RunPython(crear_ciclos_para_inscripciones, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='inscripcioncurso',
            name='uniq_inscripcion_historial',
        ),
        migrations.RemoveIndex(
            model_name='inscripcioncurso',
            name='asociados_i_ciclo_l_767aa4_idx',
        ),
        migrations.RenameField(
            model_name='inscripcioncurso',
            old_name='ciclo_lectivo',
            new_name='ciclo_lectivo_anio',
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='ciclo_lectivo',
            field=models.ForeignKey(blank=True, help_text='Año lectivo de esta inscripción.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='asociados.ciclolectivo', verbose_name='ciclo lectivo'),
        ),
        migrations.RunPython(asignar_ciclos_a_inscripciones, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='ciclo_lectivo',
            field=models.ForeignKey(help_text='Año lectivo de esta inscripción.', on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='asociados.ciclolectivo', verbose_name='ciclo lectivo'),
        ),
        migrations.RemoveField(
            model_name='inscripcioncurso',
            name='ciclo_lectivo_anio',
        ),
        migrations.AlterModelOptions(
            name='inscripcioncurso',
            options={'ordering': ['-ciclo_lectivo__anio', '-fecha_desde'], 'verbose_name': 'Inscripción a curso', 'verbose_name_plural': 'Inscripciones a curso'},
        ),
        migrations.AlterField(
            model_name='colegio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el colegio participa activamente en el sistema.', verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección física del colegio.', max_length=255, null=True, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo de contacto del colegio.', max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='nombre',
            field=models.CharField(help_text='Nombre de la institución educativa.', max_length=150, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='colegio',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto del colegio.', max_length=50, null=True, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el curso está activo en el sistema.', verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='colegio',
            field=models.ForeignKey(help_text='Colegio al que pertenece el curso.', on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='asociados.colegio', verbose_name='colegio'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(help_text='Nombre del curso, por ejemplo: 1° 1°.', max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si esta es la inscripción vigente del asociado.', verbose_name='activa'),
        ),
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='asociado',
            field=models.ForeignKey(help_text='Asociado inscripto en el curso.', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='asociados.asociado', verbose_name='asociado'),
        ),
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='curso',
            field=models.ForeignKey(help_text='Curso en el que está inscripto el asociado.', on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='asociados.curso', verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='fecha_desde',
            field=models.DateField(help_text='Fecha de inicio de esta inscripción.', verbose_name='fecha desde'),
        ),
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='fecha_hasta',
            field=models.DateField(blank=True, help_text='Fecha de fin de esta inscripción. Vacío si sigue activa.', null=True, verbose_name='fecha hasta'),
        ),
        migrations.AddIndex(
            model_name='inscripcioncurso',
            index=models.Index(fields=['ciclo_lectivo'], name='asociados_i_ciclo_l_af39a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscripcioncurso',
            constraint=models.UniqueConstraint(fields=('asociado', 'curso', 'ciclo_lectivo', 'fecha_desde'), name='uniq_inscripcion_historial'),
        ),
    ]
