# Generated by Django 5.0.3 on 2026-06-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados', '0002_ciclolectivo_alter_inscripcioncurso_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='curso',
            name='uniq_curso_por_colegio',
        ),
        migrations.RemoveIndex(
            model_name='curso',
            name='asociados_c_colegio_c5129a_idx',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='colegio',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nombre',
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['division', 'anio', 'curso', 'turno'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='anio',
            field=models.CharField(blank=True, default='', help_text='Año que cursa, ej: 1ro, 2do, 3ro.', max_length=10, verbose_name='año'),
        ),
        migrations.AddField(
            model_name='curso',
            name='curso',
            field=models.CharField(blank=True, default='', help_text='División o número de curso, ej: 1ra, 2da, única.', max_length=10, verbose_name='curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='division',
            field=models.CharField(choices=[('CB', 'Ciclo Básico'), ('CS', 'Ciclo Superior')], default='CB', help_text='Ciclo al que pertenece: CB (Ciclo Básico) o CS (Ciclo Superior).', max_length=2, verbose_name='división'),
        ),
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.CharField(choices=[('TM', 'Turno Mañana'), ('TT', 'Turno Tarde')], default='TM', help_text='Turno: TM (Turno Mañana) o TT (Turno Tarde).', max_length=2, verbose_name='turno'),
        ),
        migrations.AddConstraint(
            model_name='curso',
            constraint=models.UniqueConstraint(fields=('anio', 'curso', 'division', 'turno'), name='uniq_curso'),
        ),
        migrations.DeleteModel(
            name='Colegio',
        ),
    ]
