# Generated by Django 5.0.3 on 2026-06-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados', '0003_remove_curso_colegio_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='anio',
            field=models.CharField(help_text='Año que cursa, ej: 1ro, 2do, 3ro.', max_length=10, verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso',
            field=models.CharField(help_text='División o número de curso, ej: 1ra, 2da, única.', max_length=10, verbose_name='curso'),
        ),
    ]
