# Generated by Django 5.0.3 on 2026-06-04 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociados', '0004_alter_curso_anio_alter_curso_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InscripcionCurso',
        ),
    ]
