# Generated by Django 5.0.3 on 2026-06-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados', '0005_delete_inscripcioncurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asociado',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='asociado',
            name='direccion',
            field=models.CharField(blank=True, help_text='Domicilio del asociado.', max_length=255, verbose_name='dirección'),
        ),
    ]
