# Generated by Django 5.2.14 on 2026-08-26 13:51

import asociados.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados', '0008_clasificacionadherente_asociado_clasificacion_adherente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteSolicitudPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('clave_hash', models.CharField(max_length=64, verbose_name='resumen de la clave')),
                ('ventana_inicio', models.DateTimeField(verbose_name='inicio de la ventana')),
                ('intentos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Límite de solicitud pública',
                'verbose_name_plural': 'Límites de solicitudes públicas',
                'ordering': ['-ventana_inicio', '-id'],
                'constraints': [models.UniqueConstraint(fields=('accion', 'clave_hash', 'ventana_inicio'), name='uniq_limite_solicitud_publica')],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAsociacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[asociados.validators.validar_nombre_persona])),
                ('apellido', models.CharField(max_length=100, validators=[asociados.validators.validar_nombre_persona])),
                ('dni', models.CharField(help_text='Se conserva tal como fue declarado.', max_length=30, verbose_name='DNI o documento')),
                ('dni_normalizado', models.CharField(editable=False, help_text='Valor comparable sin espacios, puntos ni guiones.', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30, validators=[asociados.validators.validar_telefono])),
                ('direccion', models.CharField(max_length=255, verbose_name='domicilio')),
                ('es_estudiante_cet3', models.BooleanField(verbose_name='es estudiante del CET 3')),
                ('tipo', models.CharField(choices=[('asociado', 'Asociado'), ('adherente', 'Adherente')], editable=False, max_length=20)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('observada', 'Observada'), ('datos_aprobados', 'Documentación aprobada'), ('alta_completada', 'Alta completada'), ('cancelada', 'Cancelada')], default='recibida', max_length=30)),
                ('token_seguimiento_hash', models.CharField(editable=False, max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'El resumen del token es inválido.')], verbose_name='resumen del token de seguimiento')),
                ('token_seguimiento_vence_en', models.DateTimeField(verbose_name='vencimiento del enlace')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('asociado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitud_origen', to='asociados.asociado')),
                ('clasificacion_adherente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_asociacion', to='asociados.clasificacionadherente', verbose_name='clasificación de adherente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asociacion_creadas', to=settings.AUTH_USER_MODEL)),
                ('curso_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_asociacion', to='asociados.curso')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asociacion_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de asociación',
                'verbose_name_plural': 'Solicitudes de asociación',
                'ordering': ['-creado_en', '-id'],
                'indexes': [models.Index(fields=['estado', 'creado_en'], name='asociados_s_estado_09da57_idx'), models.Index(fields=['tipo'], name='asociados_s_tipo_3c57d0_idx'), models.Index(fields=['curso_actual'], name='asociados_s_curso_a_fd0ab2_idx'), models.Index(fields=['clasificacion_adherente'], name='asociados_s_clasifi_650688_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('dni_normalizado',), name='uniq_solicitud_dni_no_cancelada')],
            },
        ),
    ]
