# Generated by Django 5.2.14 on 2026-09-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados', '0009_limitesolicitudpublica_solicitudasociacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudasociacion',
            name='estado',
            field=models.CharField(choices=[('recibida', 'Recibida'), ('observada', 'Observada'), ('datos_aprobados', 'Datos aprobados'), ('alta_completada', 'Alta completada'), ('cancelada', 'Cancelada')], default='recibida', max_length=30),
        ),
    ]
