# Generated by Django 5.2.14 on 2026-09-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociados', '0010_alter_solicitudasociacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudasociacion',
            name='clave_operacion',
            field=models.UUIDField(blank=True, editable=False, help_text='Identifica el envío original para confirmar un reintento sin duplicar la solicitud ni su correo. Las solicitudes históricas pueden no tener clave.', null=True, unique=True, verbose_name='clave de operación'),
        ),
    ]
