# Generated by Django 5.0.3 on 2026-06-22 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('comercios', '0001_initial'), ('comercios', '0002_alter_comercio_ciudad_alter_comercio_email_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del rubro o actividad principal del comercio.', max_length=100, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Actividad comercial',
                'verbose_name_plural': 'Actividades comerciales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre público del comercio adherido.', max_length=150, verbose_name='nombre')),
                ('propietario', models.CharField(blank=True, help_text='Nombre de la persona propietaria o referente del comercio.', max_length=150, null=True, verbose_name='propietario')),
                ('beneficio_texto', models.TextField(help_text='Texto público que describe el beneficio vigente del comercio.', verbose_name='beneficio')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('vencido', 'Vencido'), ('baja', 'Baja')], default='pendiente', help_text='Estado del convenio con el comercio.', max_length=20, verbose_name='estado')),
                ('fecha_convenio', models.DateField(blank=True, help_text='Fecha en que se firmó o registró el convenio.', null=True, verbose_name='fecha de convenio')),
                ('notas', models.TextField(blank=True, help_text='Notas internas para seguimiento administrativo.', null=True, verbose_name='notas')),
                ('flyer_disponible', models.BooleanField(default=False, help_text='Indica si existe un flyer o pieza de difusión disponible.', verbose_name='flyer disponible')),
                ('email', models.EmailField(blank=True, help_text='Correo público o de contacto del comercio.', max_length=254, null=True, verbose_name='email')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono público o de contacto del comercio.', max_length=50, null=True, verbose_name='teléfono')),
                ('direccion', models.CharField(help_text='Dirección física del comercio.', max_length=255, verbose_name='dirección')),
                ('url_presencia_web', models.URLField(blank=True, help_text='URL pública del sitio, red social o presencia web del comercio.', null=True, verbose_name='presencia web')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad donde se encuentra el comercio.', max_length=100, null=True, verbose_name='ciudad')),
                ('provincia', models.CharField(blank=True, help_text='Provincia donde se encuentra el comercio.', max_length=100, null=True, verbose_name='provincia')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada de latitud para uso futuro en mapa.', max_digits=9, null=True, verbose_name='latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada de longitud para uso futuro en mapa.', max_digits=9, null=True, verbose_name='longitud')),
                ('actividad_comercial', models.ForeignKey(help_text='Rubro o actividad principal del comercio.', on_delete=django.db.models.deletion.PROTECT, related_name='comercios', to='comercios.actividadcomercial', verbose_name='actividad comercial')),
                ('usuario', models.OneToOneField(blank=True, help_text='Usuario que puede iniciar sesión como este comercio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comercio', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Comercio',
                'verbose_name_plural': 'Comercios',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['estado', 'nombre'], name='comercios_c_estado_a6d043_idx')],
            },
        ),
    ]
