# Generated by Django 5.0.3 on 2026-05-22 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('url_presencia_web', models.URLField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comercio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comercio',
                'verbose_name_plural': 'Comercios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BeneficioComercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto fijo'), ('promocion', 'Promocion'), ('otro', 'Otro')], max_length=20)),
                ('valor_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condiciones', models.TextField(blank=True)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='comercios.comercio')),
            ],
            options={
                'verbose_name': 'Beneficio de comercio',
                'verbose_name_plural': 'Beneficios de comercio',
                'ordering': ['comercio__nombre', 'titulo'],
            },
        ),
        migrations.AddIndex(
            model_name='comercio',
            index=models.Index(fields=['activo', 'nombre'], name='comercios_c_activo_c041de_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiocomercio',
            index=models.Index(fields=['comercio', 'activo'], name='comercios_b_comerci_79f4b3_idx'),
        ),
        migrations.AddIndex(
            model_name='beneficiocomercio',
            index=models.Index(fields=['fecha_desde', 'fecha_hasta'], name='comercios_b_fecha_d_4264d3_idx'),
        ),
    ]
