# Generated by Django 5.0.3 on 2026-06-02 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Actividad comercial',
                'verbose_name_plural': 'Actividades comerciales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('propietario', models.CharField(blank=True, max_length=150)),
                ('beneficio_texto', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('vencido', 'Vencido'), ('baja', 'Baja')], default='pendiente', max_length=20)),
                ('fecha_convenio', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('flyer_disponible', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('url_presencia_web', models.URLField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actividad_comercial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comercios', to='comercios.actividadcomercial')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comercio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comercio',
                'verbose_name_plural': 'Comercios',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['estado', 'nombre'], name='comercios_c_estado_a6d043_idx')],
            },
        ),
    ]
