# Generated by Django 5.0.3 on 2026-06-03 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='beneficio_texto',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='comercio',
            constraint=models.CheckConstraint(check=models.Q(('beneficio_texto', ''), _negated=True), name='comercio_beneficio_texto_no_vacio'),
        ),
    ]
