# Generated by Django 5.2.14 on 2026-06-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad donde se encuentra el comercio.', max_length=100, null=True, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo público o de contacto del comercio.', max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas internas para seguimiento administrativo.', null=True, verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='propietario',
            field=models.CharField(blank=True, help_text='Nombre de la persona propietaria o referente del comercio.', max_length=150, null=True, verbose_name='propietario'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='provincia',
            field=models.CharField(blank=True, help_text='Provincia donde se encuentra el comercio.', max_length=100, null=True, verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono público o de contacto del comercio.', max_length=50, null=True, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='comercio',
            name='url_presencia_web',
            field=models.URLField(blank=True, help_text='URL pública del sitio, red social o presencia web del comercio.', null=True, verbose_name='presencia web'),
        ),
    ]
