# Generated by Django 5.0.3 on 2026-06-03

import django.db.models.deletion
from django.db import migrations, models


def asignar_actividad_a_comercios_sin_clasificar(apps, schema_editor):
    actividad_model = apps.get_model("comercios", "ActividadComercial")
    comercio_model = apps.get_model("comercios", "Comercio")
    actividad, _ = actividad_model.objects.get_or_create(nombre="Sin clasificar")
    comercio_model.objects.filter(actividad_comercial__isnull=True).update(
        actividad_comercial=actividad
    )


class Migration(migrations.Migration):

    dependencies = [
        ("comercios", "0002_alter_comercio_beneficio_texto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividadcomercial",
            name="nombre",
            field=models.CharField(
                help_text="Nombre del rubro o actividad principal del comercio.",
                max_length=100,
                unique=True,
                verbose_name="nombre",
            ),
        ),
        migrations.RunPython(
            asignar_actividad_a_comercios_sin_clasificar,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="comercio",
            name="actividad_comercial",
            field=models.ForeignKey(
                help_text="Rubro o actividad principal del comercio.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comercios",
                to="comercios.actividadcomercial",
                verbose_name="actividad comercial",
            ),
        ),
    ]
