# Generated by Django 5.0.3 on 2026-06-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercios', '0003_comercio_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='foto',
            field=models.ImageField(blank=True, help_text='Fotografía del comercio para mostrar en la sección Beneficios de la home.', null=True, upload_to='comercios/', verbose_name='foto'),
        ),
    ]
